### ISSUE TITLE
REACH crashes with long texts

### ISSUE THREAD

**Issue by guerrerosimonl** [sorgerlab/indra#1032]
Hi again!

Since a couple of days (last time we could run it properly was the 1/20), REACH commands are crashing with long texts. We're able to run them with short sentences with _indra.sources.reach.api.process_text()_, but as soon as we use a long string or _indra.sources.reach.process_pmc()_, it gets stucked for hours and doesn't give an output. The exact same thing was working perfectly last time. Could you check it out, please?

Thanks in advance!

Laura

**Comment by bgyori** [comment]
Happy to look into this but more information would be helpful: what paper/text specifically are you trying to read? Have you updated REACH itself in the last few days, or only INDRA? To determine whether it is REACH itself that gets stuck, you could try to do the reading in 3 phases: (1) download and save the text content into a file (2) run REACH independent of INDRA on the file to produce a JSON output (3) process the JSON file with INDRA. If phase (2) i.e., reading gets stuck, you could post an issue on the REACH github to see if they can determine the problem.

**Comment by bgyori** [comment]
Hi @guerrerosimonl, I looked into this more deeply and found that in `indra.sources.reach`, `process_pmc` as well as `process_nxml_file` was implemented to always use the REACH web service. It appears that the REACH web service currently gets stuck on NXML files, hence the hangup.

I submitted a PR (#1033) to make sure you can use your local REACH instance when calling `process_pmc`, e.g., 
```
from indra.sources import reach
reach.process_pmc('PMC6478693', offline=True)
```
Once merged, things should be working well again.

**Comment by guerrerosimonl** [comment]
Hi Benjamin,
Thank you for your reply and thank you generating the PR but the problem is not solved unfortunately.
Our pipeline is: 
- First we extract the text with indra.literature.get_full_text()
- Once we have the text we read the text with this command (and here we get stuck for some texts): indra.sources.reach.api.process_text()
For example, one text that gives us a problem is this one:

'Correlation between benzene and testosterone in workers exposed to urban pollution. Many studies have examined the effects of benzene on testosterone. The purpose of this study was to evaluate the possible correlation between the blood levels of benzene and the levels of testosterone. The study involved a group of 148 subjects. For every worker have been made out a blood sample for the evaluation of benzene and testosterone levels and an urine analysis for the evaluation of the levels of trans, trans-muconic acid and S-phenylmercapturic acid. We estimated the Pearson correlation coefficient between the variables in the sample and the urinary metabolites, age, length of service, gender, BMI. For the analysis of the major confounding factors it was performed a multiple linear regression. The Pearson correlation coefficiet showed: 1. a significant inverse correlation between the S-phenyl mercapturic acid and free testosterone; 2. a significant direct correlation between trans-trans muconic acid and BMI. After dividing the sample according to the median of blood benzene (161.0 ng / L), Pearson correlation coefficient showed a significant inverse correlation between the S-phenyl mercapturic acid and free testosterone in the group with values below this median. Our results, to be considered preliminary, suggest that occupational exposure to low levels of benzene, present in urban pollution, affect the blood levels of testosterone. These results need to be confirmed in future studies, with the eventual possibility of including more specific fertility tests.'

We think that this texts is actually not supposed to give any statement, but it makes the system to crash. Please note that we are not using REACH independently of INDRA. 

Thank you in advance.

**Comment by bgyori** [comment]
Are you sure you are using a local instance of REACH with the `offline=True` flag? Example:
```
from indra.sources import reach
rp = reach.process_text("Correlation between benzene and testosterone...", offline=True)
```
I suspect you are sending large amounts of text to the REACH web service which should not be used for large-scale reading, and as mentioned above, it is currently getting stuck on NXML content, as well as some texts. I tested your example and it works well for me with a local instance of REACH.
